
public class ABC {
	
	
	 
	String nombreempleado="Luis Eduardo Novoa Enciso";
	String cedulaciudadania="1070614903";
	ABC x1;
	ABC x2;
	int  HORASEXTRASFESTIVAS, HORASEXTRASNOCTURNAS, HORASEXTRASDOMINICALES;
	int TOTALDIASTRABAJADOS;
	double SUELDOBASICO;
	double VALHORA=5000;
	double PROMHRFES, PROMHRNOC, PROMHRDOM, TOTALHRFES, TOTALHRNOC, TOTALHRDOM;
	double TOTALHORAS;
	double SUELDOTOTAL;
	
	
	double SUELDO(int TOTALDIASTRABAJADOS, double SUELDOBASICO){
		this.TOTALDIASTRABAJADOS=TOTALDIASTRABAJADOS;
		this.SUELDOBASICO=SUELDOBASICO;
		TOTALDIASTRABAJADOS=30;
		return SUELDOBASICO=525000;
		
		
	
		
		
			
		
	
	
	}
	
	double SUELDO(int HORASEXTRASFESTIVAS, int HORASEXTRASNOCTURNAS, int HORASEXTRASDOMINICALES, int TOTALDIASTRABAJADAS,double SUELDOTOTAL){
		this.HORASEXTRASFESTIVAS=HORASEXTRASFESTIVAS;
		this.HORASEXTRASNOCTURNAS=HORASEXTRASNOCTURNAS;
		this.HORASEXTRASDOMINICALES=HORASEXTRASDOMINICALES;
		this.TOTALDIASTRABAJADOS=TOTALDIASTRABAJADOS;
		this.SUELDOTOTAL=SUELDOTOTAL;
		HORASEXTRASFESTIVAS=15;
		HORASEXTRASNOCTURNAS=18;
		HORASEXTRASDOMINICALES=22;
		PROMHRFES=VALHORA*1.75;
		PROMHRNOC=VALHORA*1.25;
		PROMHRDOM=VALHORA*2.25;
		TOTALHRFES=PROMHRFES*HORASEXTRASFESTIVAS;
		TOTALHRNOC=PROMHRNOC*HORASEXTRASNOCTURNAS;
		TOTALHRDOM=PROMHRDOM*HORASEXTRASDOMINICALES;
		TOTALHORAS=TOTALHRFES+TOTALHRNOC+TOTALHRDOM;
		return SUELDOTOTAL=TOTALHORAS+SUELDOBASICO;
		
		
	}
	public static void main(String[]args){
		
		ABC x1=new ABC();
		System.out.println(x1.SUELDO(30,525000));
		
		ABC x2=new ABC();
		System.out.println(x2.SUELDO(15, 18, 22, 30, 525000));
	}
	




}
	
